workflows:
  debug-apk:
    name: Debug APK Build
    max_build_duration: 120
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk

  release-apk:
    name: Release APK Build
    max_build_duration: 120
    environment:
      java: 17
    scripts:
      - name: Build Release APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/**/*.apk
